version: '{branch}-{build}'

configuration:
  - Release

skip_tags: true

build:
  project: MLAPI.Transports.sln
  verbosity: minimal

after_build:
# ENET
  - ps: Get-ChildItem *.dylib | Rename-Item -NewName { $_.Name.Replace('.dylib','.bundle') }
  - 7z a ENET.zip %APPVEYOR_BUILD_FOLDER%\EnetTransport\bin\Release\*\ENet-CSharp.dll %APPVEYOR_BUILD_FOLDER%\EnetTransport\bin\Release\*\enet.dylib %APPVEYOR_BUILD_FOLDER%\EnetTransport\bin\Release\*\enet.bundle %APPVEYOR_BUILD_FOLDER%\EnetTransport\bin\Release\*\enet.dll %APPVEYOR_BUILD_FOLDER%\EnetTransport\bin\Release\*\libenet.so %APPVEYOR_BUILD_FOLDER%\EnetTransport\bin\Release\*\EnetTransport*.*
# Ruffles
  - 7z a Ruffles.zip %APPVEYOR_BUILD_FOLDER%\RufflesTransport\bin\Release\*\Ruffles.* %APPVEYOR_BUILD_FOLDER%\RufflesTransport\bin\Release\*\RufflesTransport.*
# WebSockets
  - ps: Remove-Item WebSocketTransport\bin\Release\*\*.*
  - 7z a WebSockets.zip %APPVEYOR_BUILD_FOLDER%\WebSocketTransport\bin\Release
# LiteNetLib
  - 7z a LiteNetLib.zip %APPVEYOR_BUILD_FOLDER%\LiteNetLibTransport\bin\Release\*\LiteNetLib.* %APPVEYOR_BUILD_FOLDER%\LiteNetLibTransport\bin\Release\*\LiteNetLibTransport.*
# SteamP2P
  - ps: New-Item -ItemType Directory -Force -Path SteamP2PTransport\publish\net45
  - ps: Copy-Item SteamP2PTransport\SteamP2PTransport.cs SteamP2PTransport\publish\net45\SteamP2PTransport.cs
  - 7z a SteamP2P.zip %APPVEYOR_BUILD_FOLDER%\SteamP2PTransport\publish\*\SteamP2PTransport.cs

artifacts:
  - path: 'ENET.zip'
  - path: 'Ruffles.zip'
  - path: 'WebSockets.zip'
  - path: 'LiteNetLib.zip'
  - path: 'SteamP2P.zip'

image: Visual Studio 2017

before_build:
  - nuget restore

matrix:
  fast_finish: true
